# Generated by Django 3.0.10 on 2021-08-04 17:04

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('credit_app', '0002_auto_20210804_1301'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='email',
            field=models.EmailField(max_length=255, unique=True, validators=[django.core.validators.EmailValidator()], verbose_name='Correo electrónico'),
        ),
    ]
