# Generated by Django 3.0.10 on 2021-08-04 17:30

import credit_app.models
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('credit_app', '0003_auto_20210804_1304'),
    ]

    operations = [
        migrations.CreateModel(
            name='Credit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=300, verbose_name='Nombre')),
                ('pay_min', models.DecimalField(decimal_places=2, max_digits=15, validators=[django.core.validators.DecimalValidator], verbose_name='Pago Mínimo')),
                ('pay_max', models.DecimalField(decimal_places=2, max_digits=15, validators=[django.core.validators.DecimalValidator], verbose_name='Pago Maximo')),
                ('plazo', models.IntegerField(validators=[credit_app.models.value_positive])),
                ('birthday', models.DateField(blank=True, null=True)),
                ('type_bank', models.CharField(choices=[(1, 'Automotriz'), (2, 'Hipotecarios'), (3, 'Comerciales')], default=1, max_length=15)),
                ('address', models.CharField(max_length=200, verbose_name='Direcciónd')),
                ('bank', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='credit_app.Bank')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='credit_app.Customer')),
            ],
        ),
    ]
