# Generated by Django 3.0.10 on 2021-08-04 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('credit_app', '0004_credit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='credit',
            name='description',
            field=models.CharField(max_length=300, verbose_name='descripción'),
        ),
    ]
