# Generated by Django 3.0.10 on 2021-08-04 17:40

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('credit_app', '0005_auto_20210804_1335'),
    ]

    operations = [
        migrations.AlterField(
            model_name='credit',
            name='address',
            field=models.CharField(max_length=200, verbose_name='Dirección'),
        ),
        migrations.AlterField(
            model_name='credit',
            name='pay_max',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.0'), max_digits=8, verbose_name='Pago Maximo'),
        ),
        migrations.AlterField(
            model_name='credit',
            name='pay_min',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.0'), max_digits=8, verbose_name='Pago Mínimo'),
        ),
    ]
