# Generated by Django 3.0.10 on 2021-08-04 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('credit_app', '0006_auto_20210804_1340'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='credit',
            name='type_bank',
        ),
        migrations.AddField(
            model_name='credit',
            name='type_credit',
            field=models.CharField(choices=[('1', 'Automotriz'), ('2', 'Hipotecarios'), ('3', 'Comerciales')], default='1', max_length=15),
        ),
    ]
